### ISSUE TITLE
Theme deviation.

### ISSUE THREAD

**Issue by blowsie** [dracula/jetbrains#13]
Hi, 

Thanks for your efforts in this theme!
In the last update, the theme deviates alot from what I know, and love, and still find in other IDEs.

Example.

## Webstorm:
![image](https://user-images.githubusercontent.com/308572/70614350-46b4fc80-1c02-11ea-8d9e-dae697c09f19.png)

## VS Code:
![image](https://user-images.githubusercontent.com/308572/70614321-343ac300-1c02-11ea-821e-5025e1b858e6.png)

--- 
Is this a bug? Why has the theme deviated?

**Comment by WhiteVermouth** [comment]
- Is this a bug? NO.
- WHY? Actually, Dracula theme template only introduces a color palette, you can find the palette [here](https://github.com/dracula/dracula-theme). It means different authors may implement theme differently. But we all obey the base color palette.

**Comment by blowsie** [comment]
Well, according to the dracula github some colors are well defined.

Palette | Hex | RGB | HSL |  
-- | -- | -- | -- | --
Background | #282a36 | 40 42 54 | 231° 15% 18% |  
Current Line | #44475a | 68 71 90 | 232° 14% 31% |  
Selection | #44475a | 68 71 90 | 232° 14% 31% |  
Foreground | #f8f8f2 | 248 248 242 | 60° 30% 96% |  
Comment | #6272a4 | 98 114 164 | 225° 27% 51% |  

I assumed this plugin was following these rules or there was some "official" way of defining how the theme looks.

Either way, personally I prefer how it looked before the update.
Why? 
My method calls are more greyed out than my comments, which just seems backwards.

![image](https://user-images.githubusercontent.com/308572/70642471-29e6ec00-1c37-11ea-93cb-3d5ece0a503d.png)

**Comment by blowsie** [comment]
So i did some digging and found many of the colors are not using the color pallette at all?

**Comment by WhiteVermouth** [comment]
1. Comment color is not adopt from the palette. Because the original color may lead the comments hard to distinguish from others, see issue #1 
2. Exactly only two colors are not using the color palette:
- Comment color, according to point 1.
- Parameter color, due to color lackness in default palette.
3. Any other colors not adopt from the official palette may be inherited from JetBrains IDEs' default color scheme.
4. Other Dracula theme implementation keep some "pure white" syntax highlight like the one you see in VSCode port. I totally dislike this style, so I try to avoid such "pure white" color, which leads to this somewhat "deviated" implementation.
